version: "3.8"

x-airflow-env: &airflow-env
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-data:/var/lib/postgresql/data

  airflow-init:
    image: apache/airflow:2.10.2
    depends_on:
      - postgres
    environment:
      <<: *airflow-env
    command: bash -c "airflow db upgrade"

  webserver:
    image: apache/airflow:2.10.2
    depends_on:
      - postgres
    environment:
      <<: *airflow-env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./producer:/opt/airflow/producer
    ports:
      - "8080:8080"
    command: airflow webserver

  scheduler:
    image: apache/airflow:2.10.2
    depends_on:
      - postgres
    environment:
      <<: *airflow-env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./producer:/opt/airflow/producer
    command: airflow scheduler

volumes:
  postgres-data:
